[[team_member]]
name = "basic_collaborative_agent"
type = "agent"
start_node_base_command = "python -m demo_agent.collaborative_agent_with_situational_planning.agent --use-together --model-name meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo --wait-time 1"

[[team_member]]
name = "user"
type = "simulated_user"
start_node_base_command = "python -m collaborative_gym.command start-simulated-user-node --proactive-feedback --proactive-action"
